# Purpose: Automated version tracking and build information for reproducible research.
# Provides git commit hash, branch, timestamp, and committer details for model traceability.
# Supports embedding version metadata in output files for scientific reproducibility.
"""
CWATM Version Information Module

This module provides comprehensive version tracking and reproducibility information
for the Community Water Model (CWatM). Version information is automatically
generated by GitHub Actions during the build process to ensure accurate
traceability of model versions used in scientific simulations.

The module supports reproducible research by embedding complete version
metadata into model outputs, enabling precise replication of simulation results.

This file is automatically generated by GitHub Actions.
Do not edit manually.

Notes
-----
Version information is embedded in netCDF output files to ensure full
traceability of model versions used in hydrological simulations.
The git hash provides exact code state identification for reproducibility.
"""

# Version metadata automatically generated by GitHub Actions CI/CD pipeline
# These variables provide complete traceability for reproducible research

__git_hash__ = "8b34148c98ef8ae9e035ceae69e91f9f664321a4"      # Full SHA-1 commit hash
__git_short_hash__ = "8b34148"                                  # Abbreviated commit hash
__git_branch__ = "develop"                                      # Source git branch
__build_timestamp__ = "2025-09-04 12:09:17 UTC"               # Build generation time (UTC)
__committer_name__ = "Dor Fridman"                             # Last commit author name
__committer_email__ = "dof1985@gmail.com"                      # Last commit author email

def get_version_info():
    """
    Retrieve comprehensive CWatM version and build information.
    
    Returns complete version metadata including git repository state,
    build timestamp, and committer information for reproducibility
    and traceability purposes in hydrological modeling applications.
    
    Returns
    -------
    dict
        Dictionary containing version information with the following keys:
        
        - 'git_hash' : str
            Full SHA-1 hash of the git commit used for the build
        - 'git_short_hash' : str
            Abbreviated (7-character) SHA-1 hash for display purposes
        - 'git_branch' : str
            Git branch name from which the build was created
        - 'build_timestamp' : str
            UTC timestamp when the build was generated (ISO format)
        - 'committer_name' : str
            Name of the last committer for the build commit
        - 'committer_email' : str
            Email address of the last committer
            
    Notes
    -----
    This information is automatically generated during the CI/CD process
    and provides essential metadata for reproducible research. The git hash
    enables exact replication of model behavior by identifying the precise
    code state used for any simulation.
    
    Used internally by model output routines to embed version information
    in netCDF files for complete simulation traceability.
    """
    return {
        'git_hash': __git_hash__,
        'git_short_hash': __git_short_hash__,
        'git_branch': __git_branch__,
        'build_timestamp': __build_timestamp__,
        'committer_name': __committer_name__,
        'committer_email': __committer_email__
    }

def print_version_info():
    """
    Display formatted CWatM version information to console.
    
    Prints comprehensive version metadata in a human-readable format
    including git repository state, build information, and committer
    details. Useful for debugging, logging, and verification of
    model version during simulation setup.
    
    Parameters
    ----------
    None
    
    Returns
    -------
    None
        Version information is printed directly to standard output
        
    Notes
    -----
    Output format includes:
    - Full and abbreviated git hash for code identification
    - Git branch indicating development/release status
    - Build timestamp for temporal reference
    - Last committer information for change attribution
    
    Commonly used during model initialization to document the
    exact version being executed for simulation logs and reports.
    """
    info = get_version_info()
    print(f"CWATM Version Information:")
    print(f"  Git Hash: {info['git_hash']}")
    print(f"  Short Hash: {info['git_short_hash']}")
    print(f"  Branch: {info['git_branch']}")
    print(f"  Build Time: {info['build_timestamp']}")
    print(f"  Last Committer: {info['committer_name']} <{info['committer_email']}>")
