"""
CWATM Version Information

This file is automatically generated by GitHub Actions.
Do not edit manually.
"""

__git_hash__ = "cd56f1ea3fcf10124d3da7ab950532c851eb2b6f"
__git_short_hash__ = "cd56f1e"
__git_branch__ = "develop"
__build_timestamp__ = "2025-09-04 12:03:53 UTC"
__committer_name__ = "Dor Fridman"
__committer_email__ = "dof1985@gmail.com"

def get_version_info():
    """Return version information as a dictionary"""
    return {
        'git_hash': __git_hash__,
        'git_short_hash': __git_short_hash__,
        'git_branch': __git_branch__,
        'build_timestamp': __build_timestamp__,
        'committer_name': __committer_name__,
        'committer_email': __committer_email__
    }

def print_version_info():
    """Print version information"""
    info = get_version_info()
    print(f"CWATM Version Information:")
    print(f"  Git Hash: {info['git_hash']}")
    print(f"  Short Hash: {info['git_short_hash']}")
    print(f"  Branch: {info['git_branch']}")
    print(f"  Build Time: {info['build_timestamp']}")
    print(f"  Last Committer: {info['committer_name']} <{info['committer_email']}>")
